### ISSUE TITLE
Error when launching debug client

### ISSUE THREAD

**Issue by EccentricVamp** [architectury/architectury-loom#108]
I'm trying to use Architectury Loom for a 1.19.2 Forge mod.

I downloaded the Forge template from [Architectury Templates](https://github.com/architectury/architectury-templates/releases/tag/release_build_1660373701170).

I changed the following values in `gradle.properties`
```diff
-minecraft_version=1.18.1
+minecraft_version=1.19.2
...
-forge_version = 1.18.1-40.1.0
+forge_version = 1.19.2-43.1.1
```

I ran the Gradle "build" and "vscode" tasks.

When I launch the "Minecraft Client" debugger, I get the following error

```
[16:41:27] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgeclientuserdev, --version, MOD_DEV, --assetIndex, 1.19.2-1.19, --assetsDir, C:\Users\Eccen\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 43.1.1, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, -mixin.config, examplemod.mixins.json]
[16:41:27] [main/INFO] (Launcher) ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4.1 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0
Exception in thread "main" java.lang.module.ResolutionException: Module fmlloader reads more than one module named org.spongepowered.mixin
	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.finish(Unknown Source)
	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:130)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by shedaniel** [comment]
Have you considered downloading the 1.19.2 template directly

**Comment by EccentricVamp** [comment]
Oops. I didn't scroll down enough to see it. I'll try that.

Where there big changes the Architectury Loom Forge template between 1.18.2 and 1.19.2?

**Comment by EccentricVamp** [comment]
The 1.19.2 template fails to build due to several errors.

I fixed the errors in the template
```diff
// src/main/java/com/example/examplemod/ExampleMod.java
// Line 6
-import net.minecraftforge.event.world.ExplosionEvent;
+import net.minecraftforge.event.level.ExplosionEvent;
...
// Line 44
-        LOGGER.info("Look, I found a {}!", Items.DIAMOND.getRegistryName());
+        LOGGER.info("Look, I found a {}!", ForgeRegistries.ITEMS.getKey(Items.DIAMOND));
...
// Line 55
-        LOGGER.info("Kaboom! Something just blew up in {}!", event.getWorld());
+        LOGGER.info("Kaboom! Something just blew up in {}!", event.getLevel());
```

After fixing the errors in the template, I reran the "build" and "vscode" Gradle tasks and got the same exact error

```
[13:28:43] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgeclientuserdev, --version, MOD_DEV, --assetIndex, 1.19.2-1.19, --assetsDir, C:\Users\Eccen\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 43.0.8, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, -mixin.config, examplemod.mixins.json]
[13:28:43] [main/INFO] (Launcher) ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4.1 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0
Exception in thread "main" java.lang.module.ResolutionException: Module fmlloader reads another module named fmlloader
	at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
	at java.base/java.lang.module.Resolver.finish(Unknown Source)
	at java.base/java.lang.module.Configuration.<init>(Unknown Source)
	at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:130)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by EccentricVamp** [comment]
I've also tried
* Deleting the `.gradle` folder in the template
* Deleting the `.gradle` folder for my account
* Running the "clean" Gradle task
* Running `gradlew --refresh-dependencies`
* Deleting `.vscode/launch.json`

**Comment by EccentricVamp** [comment]
I don't think this was supposed to be fixed (I didn't see it in the changelog), but I'm still getting the error in Architectury Loom 1.0.302

**Comment by qyl27** [comment]
same problem here, my project is update from 1.18.2 and architectury loom 0.12.0-snapshot.

**Comment by EccentricVamp** [comment]
[moving new error to a separate issue]

**Comment by EccentricVamp** [comment]
Looks like several other people in Discord have the same issue

[Cannot launch Forge client or server through run configurations](https://discord.com/channels/792699517631594506/1041638172490203186/1041638172490203186)

[keep getting Module fmlloader reads another module named fmlloader](https://discord.com/channels/792699517631594506/1038978884219187250/1039500999943012382)

[anyone know wtf is going on here?](https://discord.com/channels/792699517631594506/1031068830946050078/1037434193816322159)

[All forge related tasks wont run only for me](https://discord.com/channels/792699517631594506/1020811795323179068/1020811795323179068)

**Comment by SolidBlock-cn** [comment]
Same problem for me. He happens for 0.12.0 and 1.0.

**Comment by SolidBlock-cn** [comment]
I've found a temporary fix for `Module fmlloader reads another module named fmlloader`. That's to exclude Forge in the `build.gradle`, such as:
```groovy
modImplementation("pers.solid.mod:reasonable-sorting-forge:${project.reasonable_sorting_version}-mc${reasonable_sorting_mc_version}") {
    exclude group: "net.minecraftforge"
}
```

**Comment by EccentricVamp** [comment]
I tried the temporary fix. Unfortunately, it did not work for me.

**Comment by RedstoneWizard08** [comment]
Having this issue as well ([Discord link](https://discord.com/channels/792699517631594506/1307447347260686366)):

![image](https://github.com/user-attachments/assets/c63ad3b4-4bb8-40cc-b5d7-15cbfd987d2f)

Did anyone find a fix?
