### ISSUE TITLE
Cannot use Kotlin on forge-platform-specified side

### ISSUE THREAD

**Issue by dayo05** [architectury/architectury-loom#135]
In forge execution task, classes inside the common-jar and forge platform-sided classes are loaded with setting the classpath in the argument.
When using non-java language(which also supports JVM) on forge platform-sided part, the built class files are not located on the `forge/build/java/` and this causes the `ClassNotFoundError` when using those classes from Java source code or exceptions which related mod not loaded on set the entrypoint of the mod to those classes using like [`Kotlin For Forge`](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge).

To fix this problem (only to use Kotlin) temporary, you can add 
```kt
tasks.runClient {
    classpath += project.files(File(projectDir, "build/classes/kotlin/main"))
}

tasks.runServer {
    classpath += project.files(File(projectDir, "build/classes/kotlin/main"))
}
```
this code into your gradle file(this code is for Kotlin DSL and you can use similar method in groovy code too.)

Using other languages in common part doesn't felt in this bug because it loads the `dev.jar` file which those classes are included. But if you `@ExpectPlatform` annotation, this bug will affect.
Also, using fully built jar file with external forge environment(official forge installation; multimc; etc.) will not affect to this bug because the problem is related to classpath, not remapping or creation of jar file.

I suggest to load devlibs in forge too or detect the languages(with finding the subdirectories of `forge/build`) and add classpath for them.

**Comment by Bread-NiceCat** [comment]
Issue unsolved! class from the module `kotlin` never been loaded.
```
java.lang.NoClassDefFoundError: cn/breadnicecat/reciperenderer/neoforge/NeoForgePlatformImpl
	at TRANSFORMER/reciperenderer@1.0.0/cn.breadnicecat.reciperenderer.platform.neoforge.ModPlatformImpl.get(ModPlatformImpl.java:8) ~[%23195!/:?] {re:classloading}
	at TRANSFORMER/generated_60a45e0@1/cn.breadnicecat.reciperenderer.platform.ModPlatform.get(ModPlatform.java) ~[14126630148591290662.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/generated_60a45e0@1/cn.breadnicecat.reciperenderer.utils.ModUtils.<init>(ModUtils.java:15) ~[14126630148591290662.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/generated_60a45e0@1/cn.breadnicecat.reciperenderer.utils.ModUtils.<clinit>(ModUtils.java) ~[14126630148591290662.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/generated_60a45e0@1/cn.breadnicecat.reciperenderer.RecipeRendererJeiPlugin.<clinit>(RecipeRendererJeiPlugin.java:11) ~[14126630148591290662.jar%23199!/:?] {re:classloading}
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.base/java.lang.Class.forName(Class.java:421) ~[?:?] {}
	at java.base/java.lang.Class.forName(Class.java:412) ~[?:?] {}
```
