### ISSUE TITLE
[1.20.1]Unable to load JEI correctly with Forge

### ISSUE THREAD

**Issue by Bread-NiceCat** [architectury/architectury-loom#163]
Please refer to [Issues](https://github.com/mezz/JustEnoughItems/issues/3327)
It really loaded by Forge, However ,couldn't load correctly coursed by 
```[15:24:12] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: jei, class mezz.jei.forge.JustEnoughItems
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.43.jar%23194!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.43.jar%23197!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.NoClassDefFoundError: mezz/jei/common/util/MinecraftLocaleSupplier
	at mezz.jei.forge.JustEnoughItems.<init>(JustEnoughItems.java:22) ~[jei-1.20.1-forge-15.2.0.25.jar%23200!/:15.2.0.25] {re:classloading}
	... 14 more
Caused by: java.lang.ClassNotFoundException: mezz.jei.common.util.MinecraftLocaleSupplier
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at mezz.jei.forge.JustEnoughItems.<init>(JustEnoughItems.java:22) ~[jei-1.20.1-forge-15.2.0.25.jar%23200!/:15.2.0.25] {re:classloading}
	... 14 more
```
Here's the `dependencies` 
 ```
dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"
    // Remove the next line if you don't want to depend on the API
//    modApi "dev.architectury:architectury-forge:${rootProject.architectury_version}"


    modRuntimeOnly "local:appleskin-forge-mc1.20.1:2.5.0"
//JEI
    modApi "mezz.jei:jei-1.20.1-forge-api:15.2.0.25"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}
```

**Comment by shedaniel** [comment]
You should add transitive false to JEI and also delete the project's loom gradle cache to refresh it.
Also note that you are using the api jar for runtime, which is not going to work, use the api jar for compile time and use the entire jar for the runtime.
