### ISSUE TITLE
Cannot run 1.16.5 fabric client

### ISSUE THREAD

**Issue by Mai-Lapyst** [architectury/architectury-loom#172]
When using the latest forge-fabric template (https://github.com/architectury/architectury-templates/releases/tag/release_build_1698078656340), and trying to run the fabric client via `bash ./gradlew fabric:runClient`, the process fails (stalls) with following error:

```
> Task :fabric:runClient
[Architectury Transformer] Architectury Runtime 5.2.79
[Architectury Transformer] Read classpath in 909.9 ms
[Architectury Transformer] Listening at <PATH_TO_PROJECT>/common/build/devlibs/examplemod-1.0.0-dev.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
        at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
Caused by: java.lang.IllegalStateException: duplicate fabric loader classes found on classpath: jar:file:<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.14.23/2ca7b6e98c484eb8b385f789ee3641b3808cd2dc/fabric-loader-0.14.23.jar!/net/fabricmc/loader/api/FabricLoader.class, jar:file:<PATH_TO_PROJECT>/.gradle/loom-cache/remapped_mods/loom_mappings_1_16_5_layered_hash_40359_v2/net/fabricmc/fabric-loader/0.13.2/fabric-loader-0.13.2.jar!/net/fabricmc/loader/api/FabricLoader.class
        at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:65)
        at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:347)
        ... 3 more
```

<details>
<summary>output of `bash ./gradlew fabric:runClient --info`</summary>

```
Initialized native services in: <USER_HOME>/.gradle/native
Initialized jansi services in: <USER_HOME>/.gradle/native
Received JVM installation metadata from '/usr/lib/jvm/java-17-openjdk': {JAVA_HOME=/usr/lib/jvm/java-17-openjdk, JAVA_VERSION=17.0.9, JAVA_VENDOR=N/A, RUNTIME_NAME=OpenJDK Runtime Environment, RUNTIME_VERSION=17.0.9+8, VM_NAME=OpenJDK 64-Bit Server VM, VM_VERSION=17.0.9+8, VM_VENDOR=Oracle Corporation, OS_ARCH=amd64}
Checking if the launcher JVM can be re-used for build. To be re-used, the launcher JVM needs to match the parameters required for the build process: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048M -Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=de -Duser.variant
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.4/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Starting process 'Gradle build daemon'. Working directory: <USER_HOME>/.gradle/daemon/8.4 Command: /usr/lib/jvm/java-17-openjdk/bin/java --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048M -Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=de -Duser.variant -cp <USER_HOME>/.gradle/wrapper/dists/gradle-8.4-bin/1w5dpkrfk8irigvoxmyhowfim/gradle-8.4/lib/gradle-launcher-8.4.jar -javaagent:<USER_HOME>/.gradle/wrapper/dists/gradle-8.4-bin/1w5dpkrfk8irigvoxmyhowfim/gradle-8.4/lib/agents/gradle-instrumentation-agent-8.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.4
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 0.591 secs.
The client will now receive all logging from the daemon (pid: 3395752). The daemon log file: <USER_HOME>/.gradle/daemon/8.4/daemon-3395752.out.log
Daemon will be stopped at the end of the build 
Using 16 worker leases.
Received JVM installation metadata from '/usr/lib/jvm/java-17-openjdk': {JAVA_HOME=/usr/lib/jvm/java-17-openjdk, JAVA_VERSION=17.0.9, JAVA_VENDOR=N/A, RUNTIME_NAME=OpenJDK Runtime Environment, RUNTIME_VERSION=17.0.9+8, VM_NAME=OpenJDK 64-Bit Server VM, VM_VERSION=17.0.9+8, VM_VENDOR=Oracle Corporation, OS_ARCH=amd64}
Watching the file system is configured to be enabled if available
Now considering [<PATH_TO_PROJECT>] as hierarchies to watch
File system watching is active
Starting Build
Settings evaluated using settings file '<PATH_TO_PROJECT>/settings.gradle'.
Projects loaded. Root project using build file '<PATH_TO_PROJECT>/build.gradle'.
Included projects: [root project 'architectury-example-mod', project ':common', project ':fabric', project ':forge']

> Configure project :
Evaluating root project 'architectury-example-mod' using build file '<PATH_TO_PROJECT>/build.gradle'.
Architect Plugin: 3.4.149
Architectury Loom: 1.3.358
(kotlinx.metadata.jvm.KotlinClassMetadata) with version (0.6.2-1.8.20-28) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-metadata-jvm/0.6.2/40848914d93649a068cd41d1814247292c650dfa/kotlinx-metadata-jvm-0.6.2.jar)
(org.objectweb.asm.ClassVisitor) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/9.5/dc6ea1875f4d64fbc85e1691c95b96a3d8569c90/asm-9.5.jar)
(org.objectweb.asm.tree.analysis.Analyzer) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/9.5/490bacc77de7cbc0be1a30bb3471072d705be4a4/asm-analysis-9.5.jar)
(org.objectweb.asm.commons.ClassRemapper) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/9.5/19ab5b5800a3910d30d3a3e64fdb00fd0cb42de0/asm-commons-9.5.jar)
(org.objectweb.asm.tree.ClassNode) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/9.5/fd33c8b6373abaa675be407082fdfda35021254a/asm-tree-9.5.jar)
(org.objectweb.asm.util.ASMifier) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/9.5/64b5a1fc8c1b15ed2efd6a063e976bc8d3dc5ffe/asm-util-9.5.jar)
(com.fasterxml.jackson.databind.ObjectMapper) with version (2.14.2) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.14.2/1e71fddbc80bb86f71a6345ac1e8ab8a00e7134/jackson-databind-2.14.2.jar)
(com.google.gson.Gson) with version (null) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10.1/b3add478d4382b78ea20b1671390a858002feb6c/gson-2.10.1.jar)
(com.google.common.base.Preconditions) with version (null) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/31.1-jre/60458f877d055d0c9114d9e1a2efb737b4bc282c/guava-31.1-jre.jar)
(org.apache.commons.io.FileUtils) with version (2.11.0) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.11.0/a2503f302b11ebde7ebc3df41daebe0e4eea3689/commons-io-2.11.0.jar)
Creating new SharedServiceManager(1268603128)
(kotlinx.metadata.jvm.KotlinClassMetadata) with version (0.6.2-1.8.20-28) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-metadata-jvm/0.6.2/40848914d93649a068cd41d1814247292c650dfa/kotlinx-metadata-jvm-0.6.2.jar)
(org.objectweb.asm.ClassVisitor) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/9.5/dc6ea1875f4d64fbc85e1691c95b96a3d8569c90/asm-9.5.jar)
(org.objectweb.asm.tree.analysis.Analyzer) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/9.5/490bacc77de7cbc0be1a30bb3471072d705be4a4/asm-analysis-9.5.jar)
(org.objectweb.asm.commons.ClassRemapper) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/9.5/19ab5b5800a3910d30d3a3e64fdb00fd0cb42de0/asm-commons-9.5.jar)
(org.objectweb.asm.tree.ClassNode) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/9.5/fd33c8b6373abaa675be407082fdfda35021254a/asm-tree-9.5.jar)
(org.objectweb.asm.util.ASMifier) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/9.5/64b5a1fc8c1b15ed2efd6a063e976bc8d3dc5ffe/asm-util-9.5.jar)
(com.fasterxml.jackson.databind.ObjectMapper) with version (2.14.2) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.14.2/1e71fddbc80bb86f71a6345ac1e8ab8a00e7134/jackson-databind-2.14.2.jar)
(com.google.gson.Gson) with version (null) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10.1/b3add478d4382b78ea20b1671390a858002feb6c/gson-2.10.1.jar)
(com.google.common.base.Preconditions) with version (null) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/31.1-jre/60458f877d055d0c9114d9e1a2efb737b4bc282c/guava-31.1-jre.jar)
(org.apache.commons.io.FileUtils) with version (2.11.0) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.11.0/a2503f302b11ebde7ebc3df41daebe0e4eea3689/commons-io-2.11.0.jar)
(kotlinx.metadata.jvm.KotlinClassMetadata) with version (0.6.2-1.8.20-28) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-metadata-jvm/0.6.2/40848914d93649a068cd41d1814247292c650dfa/kotlinx-metadata-jvm-0.6.2.jar)
(org.objectweb.asm.ClassVisitor) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/9.5/dc6ea1875f4d64fbc85e1691c95b96a3d8569c90/asm-9.5.jar)
(org.objectweb.asm.tree.analysis.Analyzer) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/9.5/490bacc77de7cbc0be1a30bb3471072d705be4a4/asm-analysis-9.5.jar)
(org.objectweb.asm.commons.ClassRemapper) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/9.5/19ab5b5800a3910d30d3a3e64fdb00fd0cb42de0/asm-commons-9.5.jar)
(org.objectweb.asm.tree.ClassNode) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/9.5/fd33c8b6373abaa675be407082fdfda35021254a/asm-tree-9.5.jar)
(org.objectweb.asm.util.ASMifier) with version (9.5) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/9.5/64b5a1fc8c1b15ed2efd6a063e976bc8d3dc5ffe/asm-util-9.5.jar)
(com.fasterxml.jackson.databind.ObjectMapper) with version (2.14.2) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.14.2/1e71fddbc80bb86f71a6345ac1e8ab8a00e7134/jackson-databind-2.14.2.jar)
(com.google.gson.Gson) with version (null) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10.1/b3add478d4382b78ea20b1671390a858002feb6c/gson-2.10.1.jar)
(com.google.common.base.Preconditions) with version (null) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/31.1-jre/60458f877d055d0c9114d9e1a2efb737b4bc282c/guava-31.1-jre.jar)
(org.apache.commons.io.FileUtils) with version (2.11.0) was loaded from (<USER_HOME>/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.11.0/a2503f302b11ebde7ebc3df41daebe0e4eea3689/commons-io-2.11.0.jar)

> Configure project :common
Evaluating project ':common' using build file '<PATH_TO_PROJECT>/common/build.gradle'.
Creating new SharedServiceManager(865264224)
:setting up loom dependencies
:setting up loom dependencies
Applying installer data from <USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.13.2/109bda4b44a9cfb77a889cf4d3b31e32376ed1e4/fabric-loader-0.13.2.jar
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.13.2/109bda4b44a9cfb77a889cf4d3b31e32376ed1e4/fabric-loader-0.13.2.jar), ignoring
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.14.23/2ca7b6e98c484eb8b385f789ee3641b3808cd2dc/fabric-loader-0.14.23.jar), ignoring
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.14.23/2ca7b6e98c484eb8b385f789ee3641b3808cd2dc/fabric-loader-0.14.23.jar), ignoring
Could not find refmap definition, will be using default name: examplemod-common-refmap.json
Configuring compiler arguments for Java
Adding mixin to classpath of AP config: annotationProcessor
Adding mixin to classpath of AP config: testAnnotationProcessor
Could not find refmap definition, will be using default name: examplemod-common-refmap.json
Closing SharedServiceManager(865264224)

> Configure project :fabric
Evaluating project ':fabric' using build file '<PATH_TO_PROJECT>/fabric/build.gradle'.
Creating new SharedServiceManager(1203996990)
:setting up loom dependencies
:setting up loom dependencies
Applying installer data from <USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.10.5+build.213/395f461392c21828f3ea23e725291ea088758498/fabric-loader-0.10.5+build.213.jar
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.13.2/109bda4b44a9cfb77a889cf4d3b31e32376ed1e4/fabric-loader-0.13.2.jar), ignoring
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.13.2/109bda4b44a9cfb77a889cf4d3b31e32376ed1e4/fabric-loader-0.13.2.jar), ignoring
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.14.23/2ca7b6e98c484eb8b385f789ee3641b3808cd2dc/fabric-loader-0.14.23.jar), ignoring
Found another installer JSON in (<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.14.23/2ca7b6e98c484eb8b385f789ee3641b3808cd2dc/fabric-loader-0.14.23.jar), ignoring
Could not find refmap definition, will be using default name: examplemod-fabric-refmap.json
Configuring compiler arguments for Java
Adding mixin to classpath of AP config: annotationProcessor
Adding mixin to classpath of AP config: testAnnotationProcessor
Could not find refmap definition, will be using default name: examplemod-fabric-refmap.json
Closing SharedServiceManager(1203996990)

> Configure project :forge
Evaluating project ':forge' using build file '<PATH_TO_PROJECT>/forge/build.gradle'.
Creating new SharedServiceManager(330078889)
:setting up loom dependencies
:migrated srg fields in 75.19 μs
:setting up loom dependencies
Could not find refmap definition, will be using default name: examplemod-forge-refmap.json
Configuring compiler arguments for Java
Adding mixin to classpath of AP config: annotationProcessor
Adding mixin to classpath of AP config: testAnnotationProcessor
Could not find refmap definition, will be using default name: examplemod-forge-refmap.json
Closing SharedServiceManager(330078889)
All projects evaluated.
Task path 'fabric:runClient' matched project ':fabric'
Task name matched 'runClient'
Selected primary task 'runClient' from project :fabric
Tasks to be executed: [task ':common:compileJava', task ':common:processResources', task ':common:classes', task ':common:jar', task ':fabric:compileJava', task ':fabric:processResources', task ':fabric:classes', task ':fabric:generateDLIConfig', task ':fabric:generateLog4jConfig', task ':fabric:generateRemapClasspath', task ':fabric:prepareArchitecturyTransformer', task ':fabric:configureLaunch', task ':fabric:downloadAssets', task ':fabric:extractNatives', task ':fabric:configureClientLaunch', task ':fabric:runClient']
Tasks that were excluded: []
Resolve mutations for :common:compileJava (Thread[Execution worker Thread 2,5,main]) started.
:common:compileJava (Thread[Execution worker Thread 2,5,main]) started.

> Task :common:compileJava UP-TO-DATE
Watching 3 directories to track changes
Watching 4 directories to track changes
Watching 5 directories to track changes
Watching 8 directories to track changes
Watching 9 directories to track changes
Watching 10 directories to track changes
Watching 11 directories to track changes
Watching 12 directories to track changes
Watching 13 directories to track changes
Watching 14 directories to track changes
Caching disabled for task ':common:compileJava' because:
  Build cache is disabled
Skipping task ':common:compileJava' as it is up-to-date.
No compile result for :common:compileJava
No compile result for :common:compileJava
No compile result for :common:compileJava
No compile result for :common:compileJava
No compile result for :common:compileJava
No compile result for :common:compileJava
Resolve mutations for :common:processResources (Thread[Execution worker Thread 2,5,main]) started.
:common:processResources (Thread[Execution worker Thread 2,5,main]) started.

> Task :common:processResources UP-TO-DATE
Watching 18 directories to track changes
Watching 22 directories to track changes
Caching disabled for task ':common:processResources' because:
  Build cache is disabled
Skipping task ':common:processResources' as it is up-to-date.
Resolve mutations for :common:classes (Thread[Execution worker Thread 2,5,main]) started.
:common:classes (Thread[Execution worker Thread 2,5,main]) started.

> Task :common:classes UP-TO-DATE
Skipping task ':common:classes' as it has no actions.
Resolve mutations for :common:jar (Thread[Execution worker Thread 2,5,main]) started.
:common:jar (Thread[Execution worker Thread 2,5,main]) started.

> Task :common:jar UP-TO-DATE
Watching 23 directories to track changes
Watching 24 directories to track changes
Caching disabled for task ':common:jar' because:
  Build cache is disabled
Skipping task ':common:jar' as it is up-to-date.
work action resolve examplemod-dev.jar (project :common) (Thread[Execution worker Thread 2,5,main]) started.
Resolve mutations for :fabric:compileJava (Thread[Execution worker Thread 2,5,main]) started.
:fabric:compileJava (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:compileJava UP-TO-DATE
Watching 28 directories to track changes
Watching 32 directories to track changes
Watching 33 directories to track changes
Watching 34 directories to track changes
Watching 35 directories to track changes
Watching 36 directories to track changes
Watching 37 directories to track changes
Watching 38 directories to track changes
Watching 39 directories to track changes
Watching 40 directories to track changes
Watching 41 directories to track changes
Watching 42 directories to track changes
Watching 43 directories to track changes
Watching 44 directories to track changes
Watching 45 directories to track changes
Watching 46 directories to track changes
Watching 47 directories to track changes
Watching 48 directories to track changes
Watching 49 directories to track changes
Watching 50 directories to track changes
Watching 51 directories to track changes
Watching 52 directories to track changes
Watching 53 directories to track changes
Watching 54 directories to track changes
Watching 55 directories to track changes
Watching 56 directories to track changes
Watching 57 directories to track changes
Watching 58 directories to track changes
Watching 59 directories to track changes
Watching 60 directories to track changes
Watching 61 directories to track changes
Watching 62 directories to track changes
Watching 63 directories to track changes
Watching 64 directories to track changes
Watching 65 directories to track changes
Watching 66 directories to track changes
Watching 67 directories to track changes
Watching 68 directories to track changes
Watching 69 directories to track changes
Watching 70 directories to track changes
Watching 71 directories to track changes
Watching 72 directories to track changes
Watching 73 directories to track changes
Watching 74 directories to track changes
Watching 75 directories to track changes
Watching 76 directories to track changes
Watching 77 directories to track changes
Watching 78 directories to track changes
Watching 79 directories to track changes
Watching 80 directories to track changes
Watching 81 directories to track changes
Watching 82 directories to track changes
Watching 83 directories to track changes
Watching 84 directories to track changes
Caching disabled for task ':fabric:compileJava' because:
  Build cache is disabled
Skipping task ':fabric:compileJava' as it is up-to-date.
No compile result for :fabric:compileJava
No compile result for :fabric:compileJava
No compile result for :fabric:compileJava
No compile result for :fabric:compileJava
No compile result for :fabric:compileJava
No compile result for :fabric:compileJava
Resolve mutations for :fabric:processResources (Thread[Execution worker Thread 2,5,main]) started.
:fabric:processResources (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:processResources UP-TO-DATE
Watching 85 directories to track changes
Watching 86 directories to track changes
Caching disabled for task ':fabric:processResources' because:
  Build cache is disabled
Skipping task ':fabric:processResources' as it is up-to-date.
Resolve mutations for :fabric:classes (Thread[Execution worker Thread 2,5,main]) started.
:fabric:classes (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:classes UP-TO-DATE
Skipping task ':fabric:classes' as it has no actions.
Resolve mutations for :fabric:generateDLIConfig (Thread[Execution worker Thread 2,5,main]) started.
:fabric:generateDLIConfig (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:generateDLIConfig
Caching disabled for task ':fabric:generateDLIConfig' because:
  Build cache is disabled
Task ':fabric:generateDLIConfig' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resolve mutations for :fabric:generateLog4jConfig (Thread[Execution worker Thread 2,5,main]) started.
:fabric:generateLog4jConfig (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:generateLog4jConfig
Caching disabled for task ':fabric:generateLog4jConfig' because:
  Build cache is disabled
Task ':fabric:generateLog4jConfig' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Resolve mutations for :fabric:generateRemapClasspath (Thread[Execution worker Thread 2,5,main]) started.
:fabric:generateRemapClasspath (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:generateRemapClasspath UP-TO-DATE
Watching 87 directories to track changes
Caching disabled for task ':fabric:generateRemapClasspath' because:
  Build cache is disabled
Skipping task ':fabric:generateRemapClasspath' as it is up-to-date.
Resolve mutations for :fabric:prepareArchitecturyTransformer (Thread[Execution worker Thread 2,5,main]) started.
:fabric:prepareArchitecturyTransformer (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:prepareArchitecturyTransformer
Caching disabled for task ':fabric:prepareArchitecturyTransformer' because:
  Build cache is disabled
Task ':fabric:prepareArchitecturyTransformer' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Could not find refmap definition, will be using default name: examplemod-fabric-refmap.json
Resolve mutations for :fabric:configureLaunch (Thread[Execution worker Thread 2,5,main]) started.
:fabric:configureLaunch (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:configureLaunch
Skipping task ':fabric:configureLaunch' as it has no actions.
Resolve mutations for :fabric:downloadAssets (Thread[Execution worker Thread 2,5,main]) started.
:fabric:downloadAssets (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:downloadAssets UP-TO-DATE
Watching 88 directories to track changes
Caching disabled for task ':fabric:downloadAssets' because:
  Build cache is disabled
Skipping task ':fabric:downloadAssets' as it is up-to-date.
Resolve mutations for :fabric:extractNatives (Thread[Execution worker Thread 2,5,main]) started.
:fabric:extractNatives (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:extractNatives UP-TO-DATE
Watching 89 directories to track changes
Caching disabled for task ':fabric:extractNatives' because:
  Build cache is disabled
Skipping task ':fabric:extractNatives' as it is up-to-date.
Resolve mutations for :fabric:configureClientLaunch (Thread[Execution worker Thread 2,5,main]) started.
:fabric:configureClientLaunch (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:configureClientLaunch
Skipping task ':fabric:configureClientLaunch' as it has no actions.
Resolve mutations for :fabric:runClient (Thread[Execution worker Thread 2,5,main]) started.
:fabric:runClient (Thread[Execution worker Thread 2,5,main]) started.

> Task :fabric:runClient
Caching disabled for task ':fabric:runClient' because:
  Build cache is disabled
Task ':fabric:runClient' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command '/usr/lib/jvm/java-17-openjdk/bin/java''. Working directory: <PATH_TO_PROJECT>/fabric/run Command: /usr/lib/jvm/java-17-openjdk/bin/java -Darchitectury.main.class=<PATH_TO_PROJECT>/fabric/.gradle/architectury/.main_class -Darchitectury.properties=<PATH_TO_PROJECT>/fabric/.gradle/architectury/.properties -Darchitectury.runtime.transformer=<PATH_TO_PROJECT>/fabric/.gradle/architectury/.transforms -Dfabric.dli.config=<PATH_TO_PROJECT>/fabric/.gradle/loom-cache/launch.cfg -Dfabric.dli.env=client -Dfabric.dli.main=net.fabricmc.loader.launch.knot.KnotClient -Djdk.attach.allowAttachSelf=true @/tmp/loom-classpath4317533382144511717.args -javaagent:<PATH_TO_PROJECT>/.gradle/architectury/architectury-transformer-agent.jar -Dfile.encoding=UTF-8 -Duser.country=DE -Duser.language=de -Duser.variant dev.architectury.transformer.TransformerRuntime
Successfully started process 'command '/usr/lib/jvm/java-17-openjdk/bin/java''
[Architectury Transformer] Architectury Runtime 5.2.79
[Architectury Transformer] Read classpath in 894.9 ms
[Architectury Transformer] Listening at <PATH_TO_PROJECT>/common/build/devlibs/examplemod-1.0.0-dev.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
Caused by: java.lang.IllegalStateException: duplicate fabric loader classes found on classpath: jar:file:<USER_HOME>/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.14.23/2ca7b6e98c484eb8b385f789ee3641b3808cd2dc/fabric-loader-0.14.23.jar!/net/fabricmc/loader/api/FabricLoader.class, jar:file:<PATH_TO_PROJECT>/.gradle/loom-cache/remapped_mods/loom_mappings_1_16_5_layered_hash_40359_v2/net/fabricmc/fabric-loader/0.13.2/fabric-loader-0.13.2.jar!/net/fabricmc/loader/api/FabricLoader.class
	at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:65)
	at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:347)
	... 3 more
```
</details>

**Comment by Juuxel** [comment]
This is not a Loom bug: Architectury API pulls in an older version of Fabric Loader that conflicts with the newer version that is in the template. You can fix it by adding this snippet to your fabric build.gradle:
```gradle
configurations.all {
   resolutionStrategy {
     force("net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}")
   }
}
```

**Comment by Mai-Lapyst** [comment]
> This is not a Loom bug: Architectury API pulls in an older version of Fabric Loader that conflicts with the newer version that is in the template. You can fix it by adding this snippet to your fabric build.gradle:
> 
> ```groovy-gradle
> configurations.all {
>    resolutionStrategy {
>      force("net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}")
>    }
> }
> ```

I had seen that there where different versions in the dependency declarations, but didn't knew that it actually pulls both in. I just tried around with different gradle versions & loom versions and architectury-loom 1.0 with gradle 7.4 had no issue with the project, so I thought it might be a loom bug.

Anyway; thanks for the fix, it works now!
