### ISSUE TITLE
ClassNotFoundException: cpw.mods.niofs.union.UnionPathFilter when using neoforge 20.2.86

### ISSUE THREAD

**Issue by LeoLezury** [architectury/architectury-loom#181]
Architectury Loom Version: 1.4.369
Everything worked perfectly fine when I was using neoforge 20.2.59-beta. I can use neoforge's datagen without any error.
But, as I switched neoforge to version 20.2.86 and tried to run "Minecraft Data (forge)", I got this error:
Exception in thread "main" java.lang.NoClassDefFoundError: cpw/mods/niofs/union/UnionPathFilter
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.targets.CommonDevLaunchHandler.getMcFilter(CommonDevLaunchHandler.java:97)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.targets.CommonUserdevLaunchHandler.getMinecraftPaths(CommonUserdevLaunchHandler.java:36)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:37)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:155)

Full run output:
[Architectury Transformer] Architectury Runtime 5.2.80
[Architectury Transformer] Read classpath in 8.219 s
[Architectury Transformer] Listening at D:\Java\my-mod\xplat\common\build\devlibs\my-mod-1.0.0-dev.jar
[14:40:57] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgedatauserdev, --assetIndex, 1.20.2-8, --assetsDir, C:\Users\leo20\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.neoForgeVersion, 20.2.86, --fml.fmlVersion, 1.0.16, --fml.mcVersion, 1.20.2, --fml.neoFormVersion, 20231019.002635, --all, --mod, my_mod, --output, D:\Java\my-mod\xplat\common\src\generated\resources, --existing, D:\Java\my-mod\xplat\common\src\main\resources]
[14:40:57] [main/INFO] (Launcher) ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[14:40:59] [main/WARN] (FMLConfig) Configuration file D:\Java\my-mod\xplat\forge\run\config\fml.toml is not correct. Correcting
[14:40:59] [main/INFO] (FMLConfig) Incorrect key [disableConfigWatcher] was corrected from null to false
[14:40:59] [main/INFO] (ImmediateWindowHandler) ImmediateWindowProvider not loading because launch target is forgedatauserdev
[14:40:59] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/leo20/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.5/9d1c0c3a304ae6697ecd477218fa61b850bf57fc/mixin-0.8.5.jar%23137!/ Service=ModLauncher Env=CLIENT
Exception in thread "main" java.lang.NoClassDefFoundError: cpw/mods/niofs/union/UnionPathFilter
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.targets.CommonDevLaunchHandler.getMcFilter(CommonDevLaunchHandler.java:97)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.targets.CommonUserdevLaunchHandler.getMinecraftPaths(CommonUserdevLaunchHandler.java:36)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:37)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:155)
	at MC-BOOTSTRAP/fml_loader@1.0.16/net.neoforged.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
Caused by: java.lang.ClassNotFoundException: cpw.mods.niofs.union.UnionPathFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 more

**Comment by Jab125** [comment]
regenerate your run configurations

**Comment by LeoLezury** [comment]
> regenerate your run configurations

fixed. thanks for the solution and sorry for Interrupting.
