### ISSUE TITLE
NeoForge 1.20.4 crashes with the latest loom update

### ISSUE THREAD

**Issue by dima-dencep** [architectury/architectury-loom#193]
I suspect it's a [acd9ad7](https://github.com/architectury/architectury-loom/commit/acd9ad739bc990598f2a43772ea24a97ce9a2f76), loom 1.4.373 can run neoforge fine. 

```java
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getServiceProviders(ThreadContextDataInjector.java:83)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.initServiceProviders(ThreadContextDataInjector.java:73)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getProviders(ThreadContextDataInjector.java:285)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector.access$000(ThreadContextDataInjector.java:55)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ThreadContextDataInjector$ForCopyOnWriteThreadContextMap.<init>(ThreadContextDataInjector.java:226)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ContextDataInjectorFactory.createDefaultInjector(ContextDataInjectorFactory.java:94)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ContextDataInjectorFactory.createInjector(ContextDataInjectorFactory.java:71)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.ReusableLogEventFactory.<init>(ReusableLogEventFactory.java:42)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.config.LoggerConfig.<clinit>(LoggerConfig.java:96)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:136)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.1/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at MC-BOOTSTRAP/org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at MC-BOOTSTRAP/org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
	at MC-BOOTSTRAP/org.apache.logging.log4j@2.19.0/org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
```

**Comment by shedaniel** [comment]
@Juuxel what did you do 💀

**Comment by Juuxel** [comment]
Will fix 😅

**Comment by Juuxel** [comment]
Fixed by reverting the patch, I'll reintroduce a better version of it later.
