### ISSUE TITLE
IntelliJ locking up saying "loom-cache used by another process"

### ISSUE THREAD

**Issue by txnitxnichopper** [architectury/architectury-loom#195]
Randomly, when I add something and load Gradle changes, it will fail to build entirely with this error. Restarting IntelliJ does not fix it, I have to delete the loom caches in both the project directory and main Gradle cache.

```
Caused by: java.nio.file.FileSystemException: C:\Users\Anthony\IdeaProjects\sol_valheim\.gradle\loom-cache\minecraftMaven\net\minecraft\minecraft-merged-project-@fabric\1.20.1-loom.mappings.1_20_1.layered+hash.74442476-v2\minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.74442476-v2.jar: The process cannot access the file because it is being used by another process
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.ProcessedNamedMinecraftProvider.deleteSimilarJars(ProcessedNamedMinecraftProvider.java:117)
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.ProcessedNamedMinecraftProvider.processJars(ProcessedNamedMinecraftProvider.java:92)
	at net.fabricmc.loom.configuration.providers.minecraft.mapped.ProcessedNamedMinecraftProvider.provide(ProcessedNamedMinecraftProvider.java:73)
	at net.fabricmc.loom.configuration.CompileConfiguration.setupMinecraft(CompileConfiguration.java:240)
	at net.fabricmc.loom.configuration.CompileConfiguration.lambda$run$2(CompileConfiguration.java:115)
	... 196 more
```

**Comment by Juuxel** [comment]
This is not a Loom issue, it's likely Idea locking up the file.
