### ISSUE TITLE
NPE when accessing `defaultRefmapName` on Forge with ArchLoom 1.7

### ISSUE THREAD

**Issue by Johni0702** [architectury/architectury-loom#242]
Trying to set/access the `defaultRefmapName` property (among others) in a Forge project with ArchLoom 1.7 results in the following NPE:
<details>
<summary>Stacktrace</summary>

```
Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to query the value of property 'useLegacyMixinAp'.
	at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:173)
	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:163)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
	at net.fabricmc.loom.extension.MixinExtensionImpl.getDefaultRefmapName(MixinExtensionImpl.java:64)
	at net.fabricmc.loom.extension.MixinExtensionImpl_Decorated.getDefaultRefmapName(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:256)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:198)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:56)
	at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:111)
	at build_5hmndifnxn73zk31owrk82aw3$_run_closure3$_closure10.doCall$original(/tmp/groovy-generated-tmpdir-6341445609575081364/build.gradle:23)
	at build_5hmndifnxn73zk31owrk82aw3$_run_closure3$_closure10.doCall(/tmp/groovy-generated-tmpdir-6341445609575081364/build.gradle)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
	at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
	at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:107)
	at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:178)
	at net.fabricmc.loom.extension.LoomGradleExtensionApiImpl.mixin(LoomGradleExtensionApiImpl.java:306)
	at net.fabricmc.loom.extension.LoomGradleExtensionImpl_Decorated.mixin(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:218)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
	at build_5hmndifnxn73zk31owrk82aw3$_run_closure3.doCall$original(/tmp/groovy-generated-tmpdir-6341445609575081364/build.gradle:22)
	at build_5hmndifnxn73zk31owrk82aw3$_run_closure3.doCall(/tmp/groovy-generated-tmpdir-6341445609575081364/build.gradle)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
	at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:166)
	at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:107)
	at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:178)
	at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:177)
	at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
	at org.gradle.internal.extensibility.DefaultConvention.configureExtension(DefaultConvention.java:385)
	at org.gradle.internal.extensibility.DefaultConvention.access$500(DefaultConvention.java:49)
	at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:315)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:99)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:138)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.api.internal.project.DefaultDynamicLookupRoutine.invokeMethod(DefaultDynamicLookupRoutine.java:58)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:87)
	at build_5hmndifnxn73zk31owrk82aw3.run(/tmp/groovy-generated-tmpdir-6341445609575081364/build.gradle:21)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 160 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.loom.configuration.providers.forge.DependencyProviders.getProvider(java.lang.Class)" because the return value of "net.fabricmc.loom.LoomGradleExtension.getDependencyProviders()" is null
	at net.fabricmc.loom.LoomGradleExtension.getForgeProvider(LoomGradleExtension.java:202)
	at net.fabricmc.loom.extension.LoomGradleExtensionImpl_Decorated.getForgeProvider(Unknown Source)
	at net.fabricmc.loom.extension.MixinExtensionApiImpl.lambda$new$0(MixinExtensionApiImpl.java:53)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:81)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:152)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:33)
	at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:170)
	... 213 more
```

</details>

<details>
<summary>Reproduction steps</summary>

Run archloom's `ForgeSimpleMixinApTest` with the following extra line:
```patch
diff --git a/src/test/resources/projects/forge/simpleMixinAp/build.gradle b/src/test/resources/projects/forge/simpleMixinAp/build.gradle
index a8f55014..1f5e3a5c 100644
--- a/src/test/resources/projects/forge/simpleMixinAp/build.gradle
+++ b/src/test/resources/projects/forge/simpleMixinAp/build.gradle
@@ -19,6 +19,7 @@ def mcVersion = "1.18.2"
 def forgeVersion = "40.1.20"
 
 loom {
+       mixin.defaultRefmapName.set("fabric-example-mod-refmap.json")
        forge {
                mixinConfigs 'my_mixins.json'
        }
```

</details>

The [`getDefaultRefmapName` getter causes the `legacyMixinAp` property to be evaluated](https://github.com/architectury/architectury-loom/blob/c5065e813833be1560b2226c933669664e3ea90a/src/main/java/net/fabricmc/loom/extension/MixinExtensionApiImpl.java#L79).
If it hasn't been set explicitly,  [its `convention` provider](https://github.com/architectury/architectury-loom/blob/c5065e813833be1560b2226c933669664e3ea90a/src/main/java/net/fabricmc/loom/extension/MixinExtensionApiImpl.java#L53) is evaluated, which will call `LoomGradleExtension.get(project).getForgeProvider()` which will call `getDependencyProviders().getProvider(ForgeProvider.class)` which will finally NPE because the dependency providers aren't set up until `afterEvaluation`.

This wasn't an issue in ArchLoom 1.6 because the forge provider call was only added to the convention in [this commit](https://github.com/architectury/architectury-loom/commit/c040cd39d70d954673194ed576674535889399d4#diff-881ee049ded13705ad9e24890539425013432aa7ad13fd535819e065066bc25eL53-R53).

**Comment by SettingDust** [comment]
is there any workaround?

**Comment by SettingDust** [comment]
Renaming the file in jar task
```kt
rename("$id-${project.name}-${project.path.substring(1).replace(':', '_')}-refmap.json", "$id.refmap.json")
```

**Comment by Juuxel** [comment]
Fixed in 1.9.

**Comment by Johni0702** [comment]
I haven't yet tried it, but there's more methods which evaluate `legacyMixinAp` when called, so I fear any of the following still results in the same NPE:
```
sourceSets { example {} }
loom.mixin.add(sourceSets.example, "example.refmap.json")
```
```
mixin.refmapTargetNamespace.set("idk")
```

**Comment by Juuxel** [comment]
Ah, that's true. I'll probably just disable the check on Forge then, then the other platforms can still have it.
