### ISSUE TITLE
Can't run NeoForge's dataGen with Architectury Loom

### ISSUE THREAD

**Issue by Craftjakob** [architectury/architectury-loom#259]
Using Architectury Loom 1.9
I am always using the newest Minecraft, Fabric and NeoForge version.

In Architectury Loom 1.7 everything worked fine, but now I can't build a project with this version. :c

When running runData with this configuration:
build.gradle : neoforge
```
loom {
    neoForge {
        runs {
            data {
                data()
                programArgs '--mod', '--all', "${mod_id}"
                programArgs '--output', project(':common').file('src/generated/resources').getAbsolutePath()
                programArgs '--existing', project(':common').file('src/main/resources').getAbsolutePath()
            }
        }
    }
}
```
build.gradle : main
```
allprojects {
    sourceSets {
        main.resources.srcDirs = ['src/main/resources', 'src/generated/resources']
    }
}
```
This error occurs:
```
Exception in thread "main" java.lang.ClassNotFoundException: [Forge] Main class has not been determined yet!
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:85)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:220)
warning: dev-launch-injector in pass-through mode, parsing failed: java.io.IOException: invalid attribute: dataServerArgs
```

I know there is also an `clientData()` and `serverData()`, but there it says:
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$List12.indexOf(ImmutableCollections.java:597)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(ImmutableCollections.java:331)
	at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.loading.ImmediateWindowHandler.load(ImmediateWindowHandler.java:49)
	at MC-BOOTSTRAP/fml_loader@6.0.4/net.neoforged.fml.loading.ModDirTransformerDiscoverer.earlyInitialization(ModDirTransformerDiscoverer.java:42)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$17(TransformationServicesHandler.java:125)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:125)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:83)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:220)
```

I haven't found any solutions on the Architectury documentation and Discord.

When I'am looking where the problem is, I see in the RunConfigSettings.class this:
```
public void forgeTemplate(String templateName) {
        ModPlatform.assertForgeLike(this.getExtension());
        this.defaultMainClass("[Forge] Main class has not been determined yet!");
        this.evaluateNowOrLater(() -> {
            ForgeRunsProvider runsProvider = this.getExtension().getForgeRunsProvider();
            ForgeRunTemplate template = (ForgeRunTemplate)runsProvider.getTemplates().findByName(templateName);
            if (template != null) {
                template.applyTo(this, runsProvider.getResolver(this));
            } else {
                this.project.getLogger().warn("Could not find Forge run template with name '{}'", templateName);
            }

        });
    }
```

**Comment by Jab125** [comment]
is this 1.21.4? NeoForge changed how datagen worked on neoforge, see [their blog post](https://neoforged.net/news/21.4release/) and [this architectury loom commit](https://github.com/architectury/architectury-loom/commit/689ba0b8b9e303d54b5663ba670eb7bda21d11dd). Either `clientData()` or `serverData()` might work, but if it doesn't then #258 might fix that

**Comment by Craftjakob** [comment]
I do it like in the NeoForge post, but it does not work. And yes it is the 1.21.4, always the newest.

**Comment by Juuxel** [comment]
It should be functional now with 7204a7d4.
