### ISSUE TITLE
Non-mod dependencies not loading in Forge 1.17

### ISSUE THREAD

**Issue by BloCamLimb** [architectury/architectury-loom#53]
architectury-loom: 0.10.0.178

To Reproduce:
* Add non-Minecraft related dependency using `implementation` to `dependencies` block.
* Build and launch client in the development environment.

Log:
` [main/DEBUG] (net.minecraftforge.fml.loading.LibraryFinder) Found JAR manifest_jar at path: XXX dependency`
```
Caused by: java.lang.NoClassDefFoundError: [XXX dependency class here]
Caused by: java.lang.ClassNotFoundException: [XXX dependency class here]
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.46.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.46.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
```

**Comment by shedaniel** [comment]
This is mentioned in the original message for supporting Forge 1.17, I think I should mention it again.

Forge changed how it resolves modules and libraries, this is their own tutorial in getting non mod dependencies to work:
![image](https://user-images.githubusercontent.com/34910653/135027663-2b3d411d-35d6-4b7a-af09-ba4762c53ed2.jpeg)

In architectury loom however, you can add your non mod dependencies to the `forgeDependencies` configuration, loom will resolve them automatically.

Example:
```gradle
implementation(forgeDependencies("..."))
```
