### ISSUE TITLE
Architectury Forge Remapping Invalidates Dependencies

### ISSUE THREAD

**Issue by Flytre** [architectury/architectury-loom#68]
I have a pom for a forge mod with a dependency block that looks something like this:
```xml
<dependencies>
<dependency>
<groupId>org.jetbrains</groupId>
<artifactId>annotations</artifactId>
<version>23.0.0</version>
<scope>runtime</scope>
</dependency>
<dependency>
```

it's MANIFEST.MF file says:
```properties
Manifest-Version: 1.0
Multi-Release: true
```

Architectury remaps all forge dependencies without checking whether the file is indeed a mod. See --> ModCompileRemapper::shouldRemapMod

The problem is in the remapped library, the META-INF/versions folder disappears. The original library had it. This causes the remapped jar to be invalid (when it never should've been remapped in first place because it's not a mod). Jars that specify Multi-Release to be true require that folder.

Launching forge with this now broken dependency causes the expected crash:
"Exception in thread "main" java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /META-INF/versions"

**Comment by Juuxel** [comment]
Transferred this here because this is a loom bug. We can fix the unnecessary remapping, but it should also work correctly with multi-release jars, so that needs fixing too.

**Comment by CaliberMC** [comment]
Is there a fix for this?  Or a work around?

**Comment by walksanatora** [comment]
is there still no fix for this?

**Comment by CorgiTaco** [comment]
Can confirm getting the same issue in my own project: https://github.com/CorgiTaco/Enhanced-Celestials/tree/1249f5636d0de21a2af357227bdc93ed22e58ec1


Stack trace: 

```
> Task :Forge:runDatagen
[Architectury Transformer] Architectury Runtime 5.2.87
[Architectury Transformer] Read classpath in 807.9 ms
[Architectury Transformer] Listening at C:\coding\personal\Enhanced-Celestials\Common\build\devlibs\Enhanced-Celestials-Common-1.20.1-5.0.2.3-dev.jar
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 75
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
	at java.base/java.lang.String.substring(String.java:2834)
	at dev.architectury.transformer.TransformerRuntime.lambda$null$8(TransformerRuntime.java:250)
	at dev.architectury.transformer.input.BaseFileAccess.handle(BaseFileAccess.java:56)
	at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:42)
	at dev.architectury.transformer.TransformerRuntime.lambda$removeDuplicates$9(TransformerRuntime.java:246)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1755)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1743)
	at dev.architectury.transformer.TransformerRuntime.removeDuplicates(TransformerRuntime.java:240)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:214)
[18:26:25] [main/INFO] (Launcher) ModLauncher running: args [-mixin.config, enhancedcelestials.mixins.json, -mixin.config, enhancedcelestials_asm.mixins.json, -mixin.config, enhancedcelestials.forge.mixins.json, --launchTarget, forgedatauserdev, --assetIndex, 1.20.1-5, --assetsDir, C:\Users\user\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 47.3.7, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --all, --mod, enhancedcelestials, --output, C:\coding\personal\Enhanced-Celestials\Common\src\main\generated\resources, --existing, C:\coding\personal\Enhanced-Celestials\Common\src\main\resources, --mixin.config, enhancedcelestials.mixins.json, --mixin.config, enhancedcelestials_asm.mixins.json]
[18:26:25] [main/INFO] (Launcher) ModLauncher 10.0.10+10.0.10+main.22f00f84 starting: java version 21.0.6 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0
[18:26:25] [main/INFO] (ImmediateWindowHandler) ImmediateWindowProvider not loading because launch target is forgedatauserdev
[18:26:25] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/user/.gradle/caches/modules-2/files-2.1/dev.architectury/mixin-patched/0.8.5.12/cf1f787f58d3b08b0cb53ecbba7928c09a1893c8/mixin-patched-0.8.5.12.jar%23127!/ Service=ModLauncher Env=CLIENT
[18:26:26] [main/WARN] (ModFileParser) Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\javafmllanguage\1.20.1-47.3.7\5d72a04334eea2494912f0d91216648462bb32c3\javafmllanguage-1.20.1-47.3.7.jar is missing mods.toml file
[18:26:26] [main/WARN] (ModFileParser) Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\lowcodelanguage\1.20.1-47.3.7\74fd0ee16e74766d45d2efe7c74b6d0e121677df\lowcodelanguage-1.20.1-47.3.7.jar is missing mods.toml file
[18:26:26] [main/WARN] (ModFileParser) Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\mclanguage\1.20.1-47.3.7\cf753f5bc19311c127ea07e1ee43d5f9477df22b\mclanguage-1.20.1-47.3.7.jar is missing mods.toml file
[18:26:26] [main/WARN] (ModFileParser) Mod file C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\fmlcore\1.20.1-47.3.7\b6a4840dfdc56e2ae2eccdd1bf233959493d11ea\fmlcore-1.20.1-47.3.7.jar is missing mods.toml file
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file javafmllanguage-1.20.1-47.3.7.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file lowcodelanguage-1.20.1-47.3.7.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file mclanguage-1.20.1-47.3.7.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file fmlcore-1.20.1-47.3.7.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file forge-1.20.1-47.3.7-minecraft-merged-c83317604e-1.20.1-loom.mappings.1_20_1.layered+hash.1900670477-v2-forge-1.20.1-47.3.7.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file main of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
[18:26:26] [main/INFO] (ModDiscoverer) Found mod file  of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4235e01b
Exception in thread "main" java.io.UncheckedIOException: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:138)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:43)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:37)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.10/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:220)
Caused by: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions
Caused by: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions
```

Run config:
```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" factoryName="Application" name="Minecraft Datagen (:forge)" type="Application">
    <option name="MAIN_CLASS_NAME" value="dev.architectury.transformer.TransformerRuntime"/>
    <module name="ExampleMod.forge.main"/>
    <option name="PROGRAM_PARAMETERS" value="--all --mod examplemod --output C:\coding\personal\Enhanced-Celestials\common\src\main\generated\resources --existing C:\coding\personal\Enhanced-Celestials\common\src\main\resources"/>
    <option name="VM_PARAMETERS" value="-Dfabric.dli.config=C:\coding\personal\Enhanced-Celestials\forge\.gradle\loom-cache\launch.cfg -Dfabric.dli.env=data -Djava.net.preferIPv6Addresses=system -p C:\Users\user\.gradle\caches\modules-2\files-2.1\cpw.mods\securejarhandler\2.1.10\51e6a22c6c716beb11e244bf5b8be480f51dd6b5\securejarhandler-2.1.10.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\9.7\e86dda4696d3c185fcc95d8d311904e7ce38a53f\asm-commons-9.7.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-util\9.7\c0655519f24d92af2202cb681cd7c1569df6ead6\asm-util-9.7.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.7\e4a258b7eb96107106c0599f0061cfc1832fe07a\asm-analysis-9.7.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\9.7\e446a17b175bfb733b87c5c2560ccb4e57d69f1a\asm-tree-9.7.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\9.7\73d7b3086e14beb604ced229c302feff6449723\asm-9.7.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\net.minecraftforge\JarJarFileSystems\0.3.19\2464eb7d6b9ddb9db36a82cf8a95193e5c6fe020\JarJarFileSystems-0.3.19.jar --add-modules ALL-MODULE-PATH --add-opens java.base/java.util.jar=cpw.mods.securejarhandler --add-opens java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports java.base/sun.security.util=cpw.mods.securejarhandler --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Dfabric.dli.main=cpw.mods.bootstraplauncher.BootstrapLauncher -Darchitectury.main.class=C:\coding\personal\Enhanced-Celestials\forge\.gradle\architectury\.main_class -Darchitectury.runtime.transformer=C:\coding\personal\Enhanced-Celestials\forge\.gradle\architectury\.transforms -Darchitectury.properties=C:\coding\personal\Enhanced-Celestials\forge\.gradle\architectury\.properties -Djdk.attach.allowAttachSelf=true -javaagent:C:\coding\personal\Enhanced-Celestials\.gradle\architectury\architectury-transformer-agent.jar"/>
    <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$/forge/run/"/>
    <method v="2">
      <option enabled="true" name="Make"/>
    </method>
    <envs>
      <env name="MOD_CLASSES" value="main%%C:\coding\personal\Enhanced-Celestials\forge\build\resources\main;main%%C:\coding\personal\Enhanced-Celestials\forge\build\classes\java\main"/><env name="MCP_MAPPINGS" value="loom.stub"/>
    </envs>
    <shortenClasspath name="ARGS_FILE"/>
  <classpathModifications/></configuration>
</component>
```

**Comment by caoimhebyrne** [comment]
Bumping this one! It's still an issue 😔

**Comment by Ayutac** [comment]
Same problem with trying to run JCraft EoE with Fzzy Config out of dev env. Might be Jankson?

gradle deps:

    modRuntimeOnly("thedarkcolour:kotlinforforge:4.12.0")
    modRuntimeOnly("me.fzzyhmstrs:fzzy_config:0.7.3+1.20.1+forge")

Log:

	07:55:48: Executing ':forge:dev.architectury.transformer.TransformerRuntime.main()'…


	> Configure project :
	Architect Plugin: 3.4.162
	Architectury Loom: 1.9.436
	You are using an outdated version of Architectury Loom! This version will not receive any support, please consider updating!

	> Task :forge:processResources UP-TO-DATE
	> Task :common:compileJava UP-TO-DATE
	> Task :common:processResources UP-TO-DATE
	> Task :common:classes UP-TO-DATE
	> Task :common:jar UP-TO-DATE
	> Task :forge:compileJava UP-TO-DATE
	> Task :forge:classes UP-TO-DATE

	> Task :forge:dev.architectury.transformer.TransformerRuntime.main()
	[Architectury Transformer] Architectury Runtime 5.2.87
	[Architectury Transformer] Read classpath in 1.255 s
	[Architectury Transformer] Listening at C:\Users\flyhi\IdeaProjects\jcraft-eoe\common\build\devlibs\jcraft-common-0.17.6-dev.jar
	java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 54
		at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
		at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
		at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
		at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
		at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
		at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
		at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
		at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
		at java.base/java.lang.String.substring(String.java:2834)
		at dev.architectury.transformer.TransformerRuntime.lambda$null$8(TransformerRuntime.java:250)
		at dev.architectury.transformer.input.BaseFileAccess.handle(BaseFileAccess.java:56)
		at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:42)
		at dev.architectury.transformer.TransformerRuntime.lambda$removeDuplicates$9(TransformerRuntime.java:246)
		at java.base/java.util.ArrayList.removeIf(ArrayList.java:1755)
		at java.base/java.util.ArrayList.removeIf(ArrayList.java:1743)
		at dev.architectury.transformer.TransformerRuntime.removeDuplicates(TransformerRuntime.java:240)
		at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:214)
	[07:55:57] [main/INFO] (Launcher) ModLauncher running: args [--launchTarget, forgeclientuserdev, --version, MOD_DEV, --assetIndex, 1.20.1-5, --assetsDir, C:\Users\flyhi\.gradle\caches\fabric-loom\assets, --gameDir, ., --fml.forgeVersion, 47.4.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, -mixin.config, jcraft.mixins.json, -mixin.config, jcraft-forge.mixins.json, --mixin.config, jcraft.mixins.json]
	[07:55:57] [main/INFO] (Launcher) ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.8 by JetBrains s.r.o.; OS Windows 11 arch amd64 version 10.0
	[07:55:58] [main/INFO] (ImmediateWindowHandler) Loading ImmediateWindowProvider fmlearlywindow
	[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
	[07:55:58] [main/INFO] (EARLYDISPLAY) Trying GL version 4.6
	[07:55:58] [main/INFO] (EARLYDISPLAY) Requested GL version 4.6 got version 4.6
	[07:55:58] [main/INFO] (mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/flyhi/.gradle/caches/modules-2/files-2.1/dev.architectury/mixin-patched/0.8.5.12/cf1f787f58d3b08b0cb53ecbba7928c09a1893c8/mixin-patched-0.8.5.12.jar%23127!/ Service=ModLauncher Env=CLIENT
	[07:55:58] [main/WARN] (ModFileParser) Mod file C:\Users\flyhi\.gradle\caches\modules-2\files-2.1\net.minecraftforge\javafmllanguage\1.20.1-47.4.0\f0c0b352173d0a378cbdcec9cfc4ba65899a721\javafmllanguage-1.20.1-47.4.0.jar is missing mods.toml file
	[07:55:58] [main/WARN] (ModFileParser) Mod file C:\Users\flyhi\.gradle\caches\modules-2\files-2.1\net.minecraftforge\lowcodelanguage\1.20.1-47.4.0\e862740d8c84d08dbfedea412bef88fe42e727c5\lowcodelanguage-1.20.1-47.4.0.jar is missing mods.toml file
	[07:55:58] [main/WARN] (ModFileParser) Mod file C:\Users\flyhi\.gradle\caches\modules-2\files-2.1\net.minecraftforge\mclanguage\1.20.1-47.4.0\5719b3a297a33f877ed5dde4cb4bd75c859096af\mclanguage-1.20.1-47.4.0.jar is missing mods.toml file
	[07:55:58] [pool-5-thread-1/INFO] (EARLYDISPLAY) GL info: Intel(R) Iris(R) Xe Graphics GL version 4.6.0 - Build 32.0.101.7077, Intel
	[07:55:58] [main/WARN] (ModFileParser) Mod file C:\Users\flyhi\.gradle\caches\modules-2\files-2.1\net.minecraftforge\fmlcore\1.20.1-47.4.0\235975dafa4309945b59c56b53f31dc5b65a6051\fmlcore-1.20.1-47.4.0.jar is missing mods.toml file
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file javafmllanguage-1.20.1-47.4.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file lowcodelanguage-1.20.1-47.4.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file mclanguage-1.20.1-47.4.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file fmlcore-1.20.1-47.4.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file forge-1.20.1-47.4.0-minecraft-merged-4ad9563dd9-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2-forge-1.20.1-47.4.0.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file main of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	[07:55:58] [main/INFO] (ModDiscoverer) Found mod file  of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@654a4b51
	Exception in thread "main" java.io.UncheckedIOException: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions
		at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:138)
		at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:43)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:37)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:356)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
		at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
		at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:78)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:173)
		at MC-BOOTSTRAP/fmlloader@1.20.1-47.4.0/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
		at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
		at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
		at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
		at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
		at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
		at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:220)
	Caused by: cpw.mods.niofs.union.UnionFileSystem$NoSuchFileException: /META-INF/versions

**Comment by SaloEater** [comment]
Hi, any update here?

**Comment by sshcrack** [comment]
Did anyone find a fix? 😭

**Comment by SaloEater** [comment]
> Did anyone find a fix? 😭 

Nope :)

**Comment by fzzyhmstrs** [comment]
still an issue
