### ISSUE TITLE
Forge 1.16 fails to launch on 0.12

### ISSUE THREAD

**Issue by jacksonhardaway** [architectury/architectury-loom#91]
When launching Forge 1.16 on Loom 0.12 (tested with running Java 16 and 17) the game throws and exception while loading and stops.

```
[17:41:19] [main/FATAL] (FMLLoader) Missing LaunchHandler fmluserdevclient, cannot continue
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: java.lang.RuntimeException: Missing launch handler
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:174)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
[17:41:19] [main/INFO] (STDERR) [java.lang.ThreadGroup:uncaughtException:1077]: 	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)
```

**Comment by StewStrong** [comment]
Bumping for interest
