### ISSUE TITLE
Cannot launch forge mod using Arch Loom in Debug mode (Intellij)

### ISSUE THREAD

**Issue by JackTYM** [architectury/architectury-loom#95]
Ever since I migrated to Arch Loom for my forge project I haven't been able to use debug mode in Intellij.

Crash Log
```
Connected to the target VM, address: '127.0.0.1:52291', transport: 'socket'
java.lang.NoClassDefFoundError: kotlin/Result
	at kotlinx.coroutines.debug.AgentPremain.<clinit>(AgentPremain.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Exception in thread "main" FATAL ERROR in native method: processing of -javaagent failed
Disconnected from the target VM, address: '127.0.0.1:52291', transport: 'socket'

Process finished with exit code 1
```
build.gradle
```
plugins {
    id "gg.essential.loom" version "0.10.0.4"
    id "java"
    id "gg.essential.defaults" version "0.1.11"
}
sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
loom {
    launchConfigs {
        client {
            arg("--tweakClass", "gg.essential.loader.stage0.EssentialSetupTweaker")
        }
    }
}

version = "1.7.1-release"
group = "me.jacktym.aiom"

compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
    maven { url "https://repo.sk1er.club/repository/maven-public" }
    maven { url "https://repo.sk1er.club/repository/maven-releases/" }
}

configurations {
    shade
    implementation.extendsFrom(shade)
}


dependencies {
    shade("gg.essential:loader-launchwrapper:1.1.3")
    compileOnly("gg.essential:essential-1.8.9-forge:1788")
}
jar.manifest.attributes("TweakClass": "gg.essential.loader.stage0.EssentialSetupTweaker")
jar.from(configurations.shade.collect { it.isDirectory() ? it : zipTree(it) }) {
    exclude 'club.sk1er.vigilance.example.ExampleMod', 'dummyThing'
    def i = 0
    filesMatching("META-INF/NOTICE*") { name = "$name.${i++}" }
    filesMatching("META-INF/LICENSE*") { name = "$name.${i++}" }
    filesMatching("META-INF/mods.toml") { name = "$name.${i++}" }
    filesMatching("LICENSE*") { name = "$name.${i++}" }
}
jar {

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest.attributes(
            "FMLCorePluginContainsFMLMod": true,
            "FMLCorePlugin": "me.jacktym.aiomacro.FMLLoadingPlugin",
            "ForceLoadAsMod": true,
            "ModSide": "CLIENT",
            "TweakClass": "gg.essential.loader.stage0.EssentialSetupTweaker",
            "TweakOrder": "0"
    )

    enabled = false
}


processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.property("minecraft.version")
    from(sourceSets.main.resources.srcDirs) {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        filesMatching("mcmod.info") {
            expand 'version': project.version, 'mcversion': project.property("minecraft.version")
        }

    }
}

sourceSets {
    main { output.resourcesDir = java.outputDir }
}
```

Any way I can fix this? I feel like the solution could be as easy as just adding Kotlin as a dependency but I'm not fully sure, as I am using Java.

**Comment by wagyourtail** [comment]
> `id "gg.essential.loom" version "0.10.0.4"`
> `compileOnly("gg.essential:essential-1.8.9-forge:1788")`

this appears to be an unofficial fork of arch loom to support 1.8.9, you should try asking them?

**Comment by triphora** [comment]
Yep, report to them.
